### ISSUE TITLE
Picture in picture mode crash on Android 12

### ISSUE THREAD

**Issue by ibelhouchet** [BrightcoveOS/android-player-samples#251] opened 2022-03-15 10:35 UTC
Hello,
I'm trying to enable the PictureInPicture mode on on device 31+ SDK version :
`PictureInPictureManager.getInstance().enterPictureInPictureMode();`

Devices used: Pixel 5 and Pixel C
OS on both devices: Android 12
Brightcove Android SDK version: 6.16.3 

this is the error log of the crash when I try to enter to pip mode: 

```
 java.lang.IllegalArgumentException: com.nextradiotv.bfmtvandroid.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.brightcove.player.pictureinpicture.PictureInPictureManager.getDefaultRemoteActionList(PictureInPictureManager.java:447)
        at com.brightcove.player.pictureinpicture.PictureInPictureManager.getUserActions(PictureInPictureManager.java:499)
        at com.brightcove.player.pictureinpicture.PictureInPictureManager.getBrightcovePictureInPictureParams(PictureInPictureManager.java:468)
        at com.brightcove.player.pictureinpicture.PictureInPictureManager.enterPictureInPictureMode(PictureInPictureManager.java:210)
   
```

**Comment by KEAMCRF** [comment] 2022-07-08 00:16
Hi @ibelhouchet, I'm closing this issue since it isn't reproducible with the last update of the Brightcove Android SDK version 7.0.1 that now supports Android 12.

**Closed by KEAMCRF** 2022-07-08 00:16 UTC
