### ISSUE TITLE
Brightcove maven repo seriously slowing down gradle sync

### ISSUE THREAD

**Issue by darnmason** [BrightcoveOS/android-player-samples#180] opened 2018-08-16 02:14 UTC
I have found in the past week or 2 that my gradle syncs have been seriously slowed down, yesterday I had time to dive in and have a look as to why. I discovered that gradle spent most of its time scanning your repo, http://repo.brightcove.com/releases

Fed up with waiting up to 2 minutes on each run of my app I decided to pull the repo and add the Brightcove SDK manually, however then I had trouble with that method. Initially I just added the Brightcove SDK and Exoplayer2 plugin, following the instructions on your site. But I discovered that then I have to seek out all of the dependencies that these libraries require such as Exoplayer itself and stuff like requery. Perhaps I'm doing it wrong, would be interested if there's an easy way to drop the AARs in to my project.

But the real issue is why is http://repo.brightcove.com/releases so slow? Including it is causing incremental builds to take up to 2 minutes instead of up to 2 seconds. I haven't had this issue with 4 other repos.

**Comment by BCjwhisenant** [comment] 2018-08-16 19:32
Hello @darnmason   Can you add any log output to this ticket that could help us debug the issue?

**Comment by darnmason** [comment] 2018-08-17 00:35
Well just checking my .idea logs I can get confirmation of the sync time with and without the Brightcove repo. I'll have a dig to see if I can get verbose logs from Gradle sync.

Without:
2018-08-15 15:49:00,747 [thread 484]   INFO - e.project.sync.GradleSyncState - Gradle sync finished in 1 s 675 ms 
With:
2018-08-17 10:12:21,844 [thread 782]   INFO - e.project.sync.GradleSyncState - Gradle sync finished in 2 m 43 s 588 ms

**Comment by darnmason** [comment] 2018-08-17 02:14
I can't find a way to access log output when performing a sync from the IDE, which is when it's really slow. The only output I have is from the build/sync tab which appears to show errors accessing sources.

Looking at log output from a build shows a lot of 403s from hitting the Brightcove repo for other dependencies that it does not host. However, I think it's only showing the slowdown when syncing from the IDE.

synced successfully | 2 m 9 s 398 ms
-- | --
Run build | 2 m 8 s 582 ms
Load build | 17 ms
Configure build | 24 s 751 ms
allprojects | 1 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 524 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 267 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 304 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 758 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 238 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 235 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 1 s 690 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 262 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 266 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 526 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 263 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 274 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 527 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 275 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 393 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 595 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 238 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 237 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 544 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 266 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 267 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 799 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 357 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 316 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 718 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 238 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 264 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/android-sdk/6.3.1/android-sdk-6.3.1-sources.jar | 1 s 1 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.3.1/exoplayer2-6.3.1-sources.jar | 264 ms
Metadata of http://repo.brightcove.com/releases/com/brightcove/player/offline-playback/6.3.1/offline-playback-6.3.1-sources.jar | 346 ms

**Comment by MatthewPageCS** [comment] 2018-08-22 17:27
This is happening to several people at my company as well. This is probably happening to a lot of devs who pull in this repo to their app :)

**Comment by BCjwhisenant** [comment] 2018-08-24 19:18
We are looking into this issue, but at this point we're not sure as to root cause.

**Comment by peter-budo** [comment] 2018-09-17 08:15
Can we please get an update on this issue? 3 weeks and no solution is bad...

**Comment by MatthewPageCS** [comment] 2018-09-17 19:14
What my company did was mirror the brightcove repository in our local Nexus repositories, and then comment out the brightcove repo. That should work as a workaroend for anyone still having this issue until this is fixed.

**Comment by BCjwhisenant** [comment] 2018-09-17 19:34
We are still looking into this issue. The requests are for sources.jar files that we do not distribute, since our SDKs are not open-source.

**Comment by jarrodrobins** [comment] 2018-09-26 01:35
We're also having this issue. This is adding an enormous amount of time to our builds. 

Can we please can an update on this issue? It's pretty bad to have to wait this long for a fix to a problem this major.

**Comment by BCjwhisenant** [comment] 2018-09-26 18:52
Is anyone on this thread seeing this same problem with other libraries that are *not* open-source? @darnmason  you mentioned that this does not happen with 4 other repos, are those repos open- or closed-source?

Also, is it safe to assume that everyone seeing this problem (so far) is running Android Studio 3.x, and only seeing the problem during a sync within Android Studio?

We are looking into a change to repos.brightcove.com, but I expect that the error will change to a 404, instead of a 403; we are also looking into whether this might be an Android Studio issue

**Comment by BCjwhisenant** [comment] 2018-09-28 20:50
We have made a change today that has fixed this issue in our testing.
If anyone on this thread would be willing to test out a Gradle sync from Android Studio, which is where this problem was occurring, we would appreciate that.
If this problem persists, please let us know, and please include the following in your response:

**Comment by jarrodrobins** [comment] 2018-10-01 01:45
@BCjwhisenant I just tried a couple of Gradle syncs and it all looks good on my end! 

Previously, changing any dependency would result in a 10+ minute sync and now it's back down to a few seconds where it should be. 

Thanks for working it out and making the fix, I really appreciate it.

FYI I'm on Android Studio 3.2 using Brightcove SDK 6.3.0.

**Comment by BCjwhisenant** [comment] 2018-10-07 01:54
Based on testing, this issue is no longer reproducible. Closing this.

**Closed by BCjwhisenant** 2018-10-07 01:54 UTC
Labels: bug
